### ISSUE TITLE
Entity Table Validation - FluentValidation / Data Annotations

### ISSUE THREAD

**Issue by iammukeshm** [fullstackhero/blazor-wasm-boilerplate#59] opened 2021-12-28 11:40 UTC

**Comment by iammukeshm** [comment] 2021-12-28 11:41
@fretje We can use this space for discussing instead of the closed PR.

**Comment by fretje** [comment] 2021-12-28 11:55
> So, instead of dataAnnotations validator we can make use of the local FluentValidator and remove the validation dependency with NSWAG's generated code. or maybe even use both?

What do you mean with "validation dependency with nswag's generated code"?

There's not really a dependency. NSwag does generate dataannotation attributes on the generated dto's according to the openapi spec of the api.

This is simply using the default built-in blazor (data annotation) validation... This can probably be augmented with fluent validators for sure... but I've yet to see an example of that in this code base :)

**Comment by fretje** [comment] 2021-12-28 12:00
I think there's also a difference between standard blazor validation and the validation that's used inside mudblazor? I haven't really researched that yet... But from what I've seen they aren't working with <EditForm>?

**Comment by fretje** [comment] 2021-12-28 18:36
Hmmm, I started adding TCreateRequest and TUpdateRequest type parameters, but I run into the problem that the EditFormContent RenderFragment is typed and can of course only be one of those types, or I have to provide 2 fragments EditContent and UpdateContent, but then we have to copy the same thing twice again where we have to use them :-s

We're probably gonna have to resort to one extra type "TAddEditRequest" and then in the updateFunc we'll have to do the mapping manually, or in the createFunc, depending on which request type you want to use for both in the EditFormContect block.

**Comment by iammukeshm** [comment] 2021-12-29 03:28
![image](https://user-images.githubusercontent.com/31455818/147624667-c13d18df-c42e-4d80-931f-1540800ad31e.png)


Added fluentvalidation rules to Nswag using the zymlabs package. It's able to take in the validation rules we defined onto the APIClient code. and Login component seems to working now as required,

**Comment by iammukeshm** [comment] 2021-12-29 03:34
For Brands and Products, I think the issue is that we are trying to validate the Dto class instead of the Create*****Request classes where the actual fluent validators are attached.

**Comment by fretje** [comment] 2021-12-29 11:13
yet indeed, that's why I'm adding the extra type parameter... but then it's still only one (the same for create and update)...

Also: the login already worked for me with the previous code... we should better find out why it didn't work for you?

**Comment by fretje** [comment] 2021-12-29 11:20
I have seen that the brand and product services return not a problemdetails with the 400 when the validation is wrong, but our own ErrorResult... Any reason why we're not following the standard here? We don't have enough information this way to add the validation errors to the controls on the client (propertyname is missing).

I've added a ValidationErrors property to the ValidationException CustomException and put the errors in there similar like with probolemdetails, but then I run into the problem on the client that the propertynames don't have the same case because the jsonserializer changes the properties to camelcase??

I think we really should consolidate everything to one style of validation... it gets really compicated like this...

**Comment by iammukeshm** [comment] 2021-12-29 11:21
It converts the FluentValidations to equivalent DataAnnotations in the nswag generated code, which is sweet.

I see that in the API there are few places where we are still using DataAnnotations. I think it's better to switch everything to Fluent Validation to maintain consistency. I will push those changes in some time.

**Comment by iammukeshm** [comment] 2021-12-29 11:22
Yeah, can you make the 400 returns uniform throughout? It's better to follow one standard.

**Comment by iammukeshm** [comment] 2021-12-29 11:24
But i guess i already added these to the API Conventions. Wont that be enough?

```
[ProducesDefaultResponseType(typeof(ErrorResult<string>))]
    [ProducesResponseType(400, Type = typeof(HttpValidationProblemDetails))]
```

**Comment by fretje** [comment] 2021-12-29 11:30
One thing is the difference between dataannotations and fluentvalidations... 

It shouldn't be a problem to mix those up... they should in the end give the same behavior, which is returning a 400 with a problemdetails... which they don't now.

The problem is with the exceptionmiddleware, but I don't understand why we even need that. Especially as we're using "Results" as well... 

And all the controllers return IActionResults while they never do anything else then "return OK"... that's another abstraction which shouldn't be there? There seems to be quite some different patterns at work here and I'm not sure how (or even if) they work together...

**Comment by fretje** [comment] 2021-12-29 11:36
* Or your services always return results, which in the controller at the end are translated to specific actionresults (and the result isn't sent to the client, but the actual data only)
* Or your services throw exceptions, which get translated to actionresults in the exceptionmiddleware...

Not sure if it's wise to combine those 2... especially if the exceptionmiddleware sends back another type of error than the default validation...

So I'm a bit at a loss here...

**Comment by iammukeshm** [comment] 2021-12-29 11:43
the idea with ExceptionMiddleware was for catching all exceptions at one place and returning a uniform response for all errors.

**Comment by fretje** [comment] 2021-12-29 11:58
Hmmm... It's kind of a big design decision, but I think the ExceptionMiddleware should only handle "Unhandled" exceptions and we should never explicitly throw exceptions from our services...

I'm not seeing the forest through the tree's right now... there's too many things customized and not working nicely together with the things that are not customized :-s

**Comment by fretje** [comment] 2021-12-29 12:19
I am merging in your changes...

Like it is now, we can **not** put

    [ProducesResponseType(400, Type = typeof(HttpValidationProblemDetails))]

on all the actionmethods in FSHApiConventions as sometimes a 400 is sent back with an ErrorResult in stead... and there's no way to differentiate between the two... and the client even throws an exception I think... Anyway I'll leave them in for now and search for a scenario where that can be a problem...

**Comment by fretje** [comment] 2021-12-29 12:36
I've made some pull requests to show my changes:

https://github.com/fullstackhero/blazor-wasm-boilerplate/pull/62
https://github.com/fullstackhero/dotnet-webapi-boilerplate/pull/314

**Comment by fretje** [comment] 2021-12-29 13:07
Damn, now that you added the fluentvalidation schemaprocessor, I don't get there anymore :-s
Better first to implement server validation properly before doing the client validation ;-)

There will still be a need for that for validation rules that can only be run on the server for instance (e.g. checking something in the database)... maybe we should introduce one of those to be able to test this...

Anyways, there's still a problem now on the Roles AddEditModal. There a 400 is returned which is a errorresult, but gets parsed as a problemdetails... so it throws:
![image](https://user-images.githubusercontent.com/775707/147665508-388e21e0-3152-40f8-bf19-a0e788b4dac5.png)

**Comment by fretje** [comment] 2021-12-29 14:00
I think we shouldn't throw our own validationexception in our customvalidator... If I comment out those lines, validation errors are returned as HttpValidationProblemDetails, and everything works the same (at least with regards to validation...)

**Comment by fretje** [comment] 2021-12-29 14:49
It feels much better without the customvalidator, but I still get a problem with the roles...

Thats because in RolesService.RegisterRoleAsync this is thrown:

    throw new IdentityException(_localizer["Name is required"], statusCode: HttpStatusCode.BadRequest);

which results in a 400 ErrorResult again...

**Comment by fretje** [comment] 2021-12-29 20:39
Ok, most issues seem to be fixed now...

I was just trying to add a validation rule for RoleRequest, something like:

            RuleFor(p => p.Name)
                .NotEmpty()
                .MustAsync(async (name, _) => !await _roleService.RoleExistsAsync(name));

but apparently async validation is not supported in the aspnetcore pipeline :-s (https://docs.fluentvalidation.net/en/latest/async.html).

**Comment by fretje** [comment] 2021-12-30 01:09
Got it to work... the not supported part was for classic asp.net... it does work in aspnetcore apparently... it was me who made a stupid mistake :-s

see https://github.com/fullstackhero/dotnet-webapi-boilerplate/pull/319

**Closed** 2022-01-01 12:06 UTC
